[build]
  buildCommand = "npm run generate"

[deploy]
  startCommand = "npx serve .output/public --single --listen $PORT"
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
